name: NFS Automation

on:
  issues:
    types: [opened]

jobs:
  build:
    steps:
      - name: Handle new issue
        id: new-issue
        uses: ./actions/nfs-automation
        with:
          repo-token: ${{ secrets.GH_TOKEN }}